Some fixes for uwe.
On 19.03.2012 15:09, Uwe Ligges wrote:
> Dear package maintainers of filehash and lossDev,
>
> CRAN package filehash has been updated recently and causes warnings 
> for lossDev under all flavours of R and platforms:
>
> http://cran.r-project.org/web/checks/check_results_lossDev.html
>
> Can you please negotiate further actions and fix the problem. Please 
> upload fixed version(s) of the package(s) with increased version
> number(s) to CRAN in the usual way and report to cran@R-project.org.
>
> Best wishes,
> Uwe Ligges
>


Since package lossDev still gives Warnings or even Errors (3 months after my notification!) under all platforms, this has been schedulded for archival on July 9. If you want to keep it on CRAN, wen need an update by that date.

Uwe Ligges

•using R Under development (unstable) (2012-06-27 r59670) 
•using platform: x86_64-unknown-linux-gnu (64-bit) 
•using session charset: UTF-8 
•using option ‘--no-vignettes’ 
•checking for file ‘lossDev/DESCRIPTION’ ... OK 
•this is package ‘lossDev’ version ‘3.0.0-1’ 
•checking package namespace information ... OK 
•checking package dependencies ... OK 
•checking if this is a source package ... OK 
•checking if there is a namespace ... OK 
•checking for executable files ... OK 
•checking whether package ‘lossDev’ can be installed ... OK 
•checking installed package size ... OK 
•checking package directory ... OK 
•checking for portable file names ... OK 
•checking for sufficient/correct file permissions ... OK 
•checking DESCRIPTION meta-information ... OK 
•checking top-level files ... OK 
•checking index information ... OK 
•checking package subdirectories ... OK 
•checking R files for non-ASCII characters ... OK 
•checking R files for syntax errors ... OK 
•checking whether the package can be loaded ... OK 
•checking whether the package can be loaded with stated dependencies ... OK 
•checking whether the package can be unloaded cleanly ... OK 
•checking whether the namespace can be loaded with stated dependencies ... WARNING
linking to JAGS 3.2.0
module basemod loaded
module bugs loaded
module lossDev loaded
Error: .onLoad failed in loadNamespace() for ‘lossDev’, details:
call: dbCreate("lossDev.filehash", type = "RDS")
error: could not find function "loadMethod"
In addition: Warning message:
No function found corresponding to methods exports from ‘filehash’ for: ‘coerce’, ‘show’ 
Execution halted

A namespace must be able to be loaded with just the base namespace
loaded: otherwise if the namespace gets loaded by a saved object, the
session will be unable to start.

Probably some imports need to be declared in the NAMESPACE file. 
•checking whether the namespace can be unloaded cleanly ... OK 
•checking loading without being on the library search path ... OK 
•checking for unstated dependencies in R code ... OK 
•checking S3 generic/method consistency ... OK 
•checking replacement functions ... OK 
•checking foreign function calls ... OK 
•checking R code for possible problems ... NOTE
.onLoad: warning in assign("myPkgName", myPkgName, env = mutableState):
partial argument match of 'env' to 'envir'
.onLoad: warning in assign("myLibPath", myLibPath, env = mutableState):
partial argument match of 'env' to 'envir'
myLibPath: warning in get("myLibPath", env = mutableState, inherits =
FALSE): partial argument match of 'env' to 'envir'
myPkgName: warning in get("myPkgName", env = mutableState, inherits =
FALSE): partial argument match of 'env' to 'envir' 
•checking Rd files ... OK 
•checking Rd metadata ... OK 
•checking Rd cross-references ... OK 
•checking for missing documentation entries ... OK 
•checking for code/documentation mismatches ... OK 
•checking Rd \usage sections ... OK 
•checking Rd contents ... OK 
•checking for unstated dependencies in examples ... OK 
•checking contents of ‘data’ directory ... OK 
•checking data for non-ASCII characters ... OK 
•checking data for ASCII and uncompressed saves ... OK 
•checking line endings in C/C++/Fortran sources/headers ... OK 
•checking line endings in Makefiles ... OK 
•checking for portable compilation flags in Makevars ... OK 
•checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK 
•checking compiled code ... OK 
•checking sizes of PDF files under ‘inst/doc’ ... OK 
•checking installed files from ‘inst/doc’ ... OK 
•checking examples ... NONE 
•checking for unstated dependencies in tests ... OK 
•checking tests ... [23s/23s] OK
Running ‘Standard.R’ [23s/23s] 
•checking for unstated dependencies in vignettes ... OK 
•checking package vignettes in ‘inst/doc’ ... OK 
•checking running R code from vignettes ... SKIPPED 
•checking re-building of vignettes ... SKIPPED 
•checking PDF version of manual ... OK
WARNING: There was 1 warning.
NOTE: There was 1 note.
See
‘/home/hornik/tmp/R.check/r-devel/Work/PKGS/lossDev.Rcheck/00check.log’
for details.

•using R version 2.15.1 (2012-06-22) 
•using platform: x86_64-pc-mingw32 (64-bit) 
•using session charset: ISO8859-1 
•using option '--no-vignettes' 
•checking for file 'lossDev/DESCRIPTION' ... OK 
•this is package 'lossDev' version '3.0.0-1' 
•checking package namespace information ... OK 
•checking package dependencies ... OK 
•checking if this is a source package ... OK 
•checking if there is a namespace ... OK 
•checking whether package 'lossDev' can be installed ... OK 
•checking installed package size ... OK 
•checking package directory ... OK 
•checking for portable file names ... OK 
•checking DESCRIPTION meta-information ... OK 
•checking top-level files ... OK 
•checking index information ... OK 
•checking package subdirectories ... OK 
•checking R files for non-ASCII characters ... OK 
•checking R files for syntax errors ... OK 
•loading checks for arch 'i386'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... WARNING
linking to JAGS 3.1.0
module basemod loaded
module bugs loaded
module lossDev loaded
Error: .onLoad failed in loadNamespace() for 'lossDev', details:
call: dbCreate("lossDev.filehash", type = "RDS")
error: could not find function "loadMethod"
In addition: Warning message:
No function found corresponding to methods exports from 'filehash' for: 'coerce', 'show' 
Execution halted

A namespace must be able to be loaded with just the base namespace
loaded: otherwise if the namespace gets loaded by a saved object, the
session will be unable to start.

Probably some imports need to be declared in the NAMESPACE file.
** checking whether the namespace can be unloaded cleanly ... OK 
•loading checks for arch 'x64'
** checking whether the package can be loaded ... OK
** checking whether the package can be loaded with stated dependencies ... OK
** checking whether the package can be unloaded cleanly ... OK
** checking whether the namespace can be loaded with stated dependencies ... WARNING
linking to JAGS 3.1.0
module basemod loaded
module bugs loaded
module lossDev loaded
Error: .onLoad failed in loadNamespace() for 'lossDev', details:
call: dbCreate("lossDev.filehash", type = "RDS")
error: could not find function "loadMethod"
In addition: Warning message:
No function found corresponding to methods exports from 'filehash' for: 'coerce', 'show' 
Execution halted

A namespace must be able to be loaded with just the base namespace
loaded: otherwise if the namespace gets loaded by a saved object, the
session will be unable to start.

Probably some imports need to be declared in the NAMESPACE file.
** checking whether the namespace can be unloaded cleanly ... OK 
•checking for unstated dependencies in R code ... OK 
•checking S3 generic/method consistency ... OK 
•checking replacement functions ... OK 
•checking foreign function calls ... OK 
•checking R code for possible problems ... NOTE
.onLoad: warning in assign("myPkgName", myPkgName, env = mutableState):
partial argument match of 'env' to 'envir'
.onLoad: warning in assign("myLibPath", myLibPath, env = mutableState):
partial argument match of 'env' to 'envir'
myLibPath: warning in get("myLibPath", env = mutableState, inherits =
FALSE): partial argument match of 'env' to 'envir'
myPkgName: warning in get("myPkgName", env = mutableState, inherits =
FALSE): partial argument match of 'env' to 'envir' 
•checking Rd files ... OK 
•checking Rd metadata ... OK 
•checking Rd cross-references ... OK 
•checking for missing documentation entries ... OK 
•checking for code/documentation mismatches ... OK 
•checking Rd \usage sections ... OK 
•checking Rd contents ... OK 
•checking for unstated dependencies in examples ... OK 
•checking contents of 'data' directory ... OK 
•checking data for non-ASCII characters ... OK 
•checking data for ASCII and uncompressed saves ... OK 
•checking line endings in C/C++/Fortran sources/headers ... OK 
•checking line endings in Makefiles ... OK 
•checking for portable compilation flags in Makevars ... OK 
•checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK 
•checking compiled code ... OK 
•checking sizes of PDF files under 'inst/doc' ... OK 
•checking installed files from 'inst/doc' ... OK 
•checking examples ... NONE 
•checking for unstated dependencies in tests ... OK 
•checking tests ...
** running tests for arch 'i386' ERROR
Running the tests in 'tests/Standard.R' failed.
Last 13 lines of output:
Resolving undeclared variables
Allocating nodes
Graph Size: 3952

Initializing model


Deleting model

Error: RUNTIME ERROR:
unable to calculate eigenvalues in dsyev

Execution halted
** running tests for arch 'x64' ERROR
Running the tests in 'tests/Standard.R' failed.
Last 13 lines of output:
Resolving undeclared variables
Allocating nodes
Graph Size: 3952

Initializing model


Deleting model

Error: RUNTIME ERROR:
unable to calculate eigenvalues in dsyev

Execution halted 
•using check arguments '--no-vignettes'


git-svn-id: svn://svn.r-forge.r-project.org/svnroot/lossdev@192 edb9625f-4e0d-4859-8d74-9fd3b1da38cb